In [11]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)  # Output: [1 2 3]
print(type(arr))  # Output: <class 'numpy.ndarray'>

arr2d = np.array([[1, 2], [2, 7], [9, 10]])
print(arr2d)
print(type(arr2d))  # Output: <class 'numpy.ndarray'>
print(arr2d.shape)  # Output: (3, 2)

list_of_list = [[1, 2], [2, 7], [9, 10]]
print(type(list_of_list))  # Output: <class 'list'>
print(list_of_list)

print(arr + 1) # output: [2 3 4]  # Element-wise addition
print(arr ** 2) # output: [ 1  4  9]  # Element-wise squaring
print(arr * 2)  # output: [2 4 6]  # Element-wise doubling

list1 = [1, 2, 3]
print(list1 * 2) # output: [1, 2, 3, 1, 2, 3]  # List repetition

[1 2 3]
<class 'numpy.ndarray'>
[[ 1  2]
 [ 2  7]
 [ 9 10]]
<class 'numpy.ndarray'>
(3, 2)
<class 'list'>
[[1, 2], [2, 7], [9, 10]]
[2 3 4]
[1 4 9]
[2 4 6]
[1, 2, 3, 1, 2, 3]


In [18]:
arr3 = np.array([100, 8, 6, 80])
print(np.mean(arr3))  # Output: 48.5
print(np.median(arr3))  # Output: 44.0
print(np.std(arr3))  # Output: 42.1040378

arr4_reshaped = arr3.reshape(2, 2)
print(arr4_reshaped)

print(arr3.size)  # Output: 4


48.5
44.0
42.10403781111736
[[100   8]
 [  6  80]]
4
